import { useState } from 'react';
import { Download, Loader2 } from 'lucide-react';

const DownloadReport = ({ detections, risk, manifestItems }) => {
  const [isGenerating, setIsGenerating] = useState(false);
  const [isReady, setIsReady] = useState(false);

  const handleDownload = async () => {
    setIsGenerating(true);
    
    // Simulate PDF generation delay
    await new Promise(resolve => setTimeout(resolve, 2000));
    
    // Create dummy PDF content (just a text file for demo)
    const reportContent = generateReportContent();
    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    
    // Download the file
    const a = document.createElement('a');
    a.href = url;
    a.download = `customs_report_${new Date().toISOString().slice(0, 10)}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    
    setIsGenerating(false);
    setIsReady(true);
    
    // Reset ready state after 3 seconds
    setTimeout(() => setIsReady(false), 3000);
  };

  const generateReportContent = () => {
    const timestamp = new Date().toLocaleString();
    
    let content = `CUSTOMS INSPECTION REPORT\n`;
    content += `========================\n\n`;
    content += `Date and time of scan: ${timestamp}\n`;
    content += `System: Customs X-ray Intelligence Platform v1.0\n`;
    content += `Model: YOLOv8m | Dataset: CargoXray\n\n`;
    content += `RISK ASSESSMENT\n`;
    content += `----------------\n`;
    content += `Risk Level: ${risk?.level || 'UNKNOWN'}\n`;
    content += `Risk Score: ${risk?.score || 0}\n`;
    content += `Reason: ${risk?.reason || 'No reason provided'}\n\n`;
    
    if (detections && detections.length > 0) {
      content += `DETECTED ITEMS\n`;
      content += `-------------\n`;
      detections.forEach((detection, index) => {
        content += `${index + 1}. ${detection.label} - ${Math.round(detection.confidence * 100)}% (${detection.category})\n`;
      });
      content += `\n`;
    }
    
    if (manifestItems && manifestItems.length > 0) {
      content += `MANIFEST ITEMS\n`;
      content += `---------------\n`;
      manifestItems.forEach((item, index) => {
        content += `${index + 1}. ${item}\n`;
      });
      content += `\n`;
    }
    
    content += `\nMODEL PERFORMANCE\n`;
    content += `----------------\n`;
    content += `mAP@0.5: 0.924\n`;
    content += `Precision: 0.933\n`;
    content += `Recall: 0.862\n`;
    content += `Model: YOLOv8m\n`;
    content += `Dataset: CargoXray\n\n`;
    
    content += `This report was generated by an AI-assisted system. `;
    content += `Final inspection decisions must be made by a certified customs officer.\n`;
    
    return content;
  };

  return (
    <button
      onClick={handleDownload}
      disabled={isGenerating}
      className={`btn-primary w-full max-w-md mx-auto ${
        isGenerating ? 'opacity-75 cursor-not-allowed' : ''
      } ${isReady ? 'bg-emerald-600 hover:bg-emerald-700 active:bg-emerald-800' : ''}`}
    >
      {isGenerating ? (
        <>
          <Loader2 className="w-5 h-5 animate-spin" />
          <span>Generating report…</span>
        </>
      ) : isReady ? (
        <>
          <Download className="w-5 h-5" />
          <span>Report ready</span>
        </>
      ) : (
        <>
          <Download className="w-5 h-5" />
          <span>Download report</span>
        </>
      )}
    </button>
  );
};

export default DownloadReport;
