# # -*- coding: utf-8 -*-
# """YOLOv8.ipynb

# Automatically generated by Colab.

# Original file is located at
#     https://colab.research.google.com/drive/1sLWw3BWsGX2XH_W3TZgGi9nTxrEsXLeG
# """

# # Install dependencies
# !pip install ultralytics shap opencv-python-headless matplotlib pillow

# # (Optional) ngrok if you plan API serving
# !pip install pyngrok

# from google.colab import files

# # uploaded = files.upload()  # upload best.pt

# MODEL_PATH = "/content/drive/MyDrive/best.pt"

from typing import Dict, List
from PIL import Image, ImageDraw
from ultralytics import YOLO
import torch
import numpy as np
import shap
import matplotlib.pyplot as plt
import matplotlib.patches as patches
import cv2

Detection = Dict[str, object]


class XRayDetector:
    def __init__(self, model_path: str = "best.pt") -> None:
        self.device = "cuda" if torch.cuda.is_available() else "cpu"
        self.model = YOLO(model_path)
        self.model.to(self.device)

    def detect(self, image: Image.Image) -> List[Detection]:
        results = self.model(image, conf=0.25, device=self.device)
        detections: List[Detection] = []

        if not results:
            return detections

        result = results[0]
        boxes = result.boxes
        if boxes is None:
            return detections

        class_names = result.names if result.names is not None else {}

        xyxy = boxes.xyxy.cpu().tolist()
        confs = boxes.conf.cpu().tolist()
        class_ids = boxes.cls.cpu().tolist()

        for bbox, confidence, class_id in zip(xyxy, confs, class_ids):
            class_idx = int(class_id)
            label = str(class_names.get(class_idx, str(class_idx)))

            detections.append(
                {
                    "label": label,
                    "confidence": float(confidence),
                    "bbox": [float(val) for val in bbox],
                }
            )

        return detections

class YOLOShapExplainer:
    def __init__(self, detector: XRayDetector, suspicious_labels=None):
        self.detector = detector
        self.device = detector.device
        self.suspicious_labels = set(suspicious_labels or {"gun", "knife", "bullet"})
        self._target_label = None
        self._fixed_bbox = None

    # ------------------------------------------------------------
    # IoU Calculation
    # ------------------------------------------------------------
    def _iou(self, boxA, boxB):
        xA = max(boxA[0], boxB[0])
        yA = max(boxA[1], boxB[1])
        xB = min(boxA[2], boxB[2])
        yB = min(boxA[3], boxB[3])

        inter = max(0, xB - xA) * max(0, yB - yA)

        areaA = (boxA[2] - boxA[0]) * (boxA[3] - boxA[1])
        areaB = (boxB[2] - boxB[0]) * (boxB[3] - boxB[1])

        denom = areaA + areaB - inter
        return inter / denom if denom > 0 else 0.0

    # ------------------------------------------------------------
    # Soft scoring
    # ------------------------------------------------------------
    def _soft_score(self, detections):
        if not detections or self._fixed_bbox is None:
            return 0.0

        best = 0.0
        fallback = 0.0

        for d in detections:
            iou = self._iou(d["bbox"], self._fixed_bbox)
            score = d["confidence"] * iou
            best = max(best, score)
            fallback = max(fallback, d["confidence"] * 0.05)

        return best if best > 0 else fallback

    # ------------------------------------------------------------
    # Model Wrapper
    # ------------------------------------------------------------
    def _model_wrapper(self, images):
        outputs = []

        for img in images:
            img_pil = Image.fromarray(img.astype(np.uint8))
            detections = self.detector.detect(img_pil)
            outputs.append(self._soft_score(detections))

        return np.array(outputs, dtype=np.float32)

    # ------------------------------------------------------------
    # Get Top Detection
    # ------------------------------------------------------------
    def _get_top_detection(self, detections):
        suspicious = [
            d for d in detections
            if d["label"].lower() in self.suspicious_labels
        ]

        pool = suspicious if suspicious else detections

        return (
            sorted(pool, key=lambda x: x["confidence"], reverse=True)[0]
            if pool else None
        )

    # ------------------------------------------------------------
    # SHAP Interpretation
    # ------------------------------------------------------------
    def _interpret_shap(self, shap_values, top_det, threshold=0.001):
        vals = shap_values.values[0]
        pixel_importance = np.mean(np.abs(vals), axis=-1)

        pmax = pixel_importance.max()
        pixel_importance_norm = pixel_importance / pmax if pmax > 0 else pixel_importance

        positive_shap = float(np.mean(vals[vals > 0])) if np.any(vals > 0) else 0.0
        negative_shap = float(np.mean(vals[vals < 0])) if np.any(vals < 0) else 0.0
        coverage_pct = 100.0 * np.sum(pixel_importance_norm > threshold) / pixel_importance_norm.size

        flat_idx = np.argmax(pixel_importance)
        peak_y, peak_x = np.unravel_index(flat_idx, pixel_importance.shape)

        label = top_det["label"]
        confidence = top_det["confidence"]
        suspicious = label.lower() in self.suspicious_labels

        # Strength
        if coverage_pct >= 30:
            strength_label = "High"
        elif coverage_pct >= 10:
            strength_label = "Medium"
        else:
            strength_label = "Low"

        # Reliability
        if confidence >= 0.75:
            reliability = "High"
        elif confidence >= 0.5:
            reliability = "Moderate"
        else:
            reliability = "Low"

        # Verdict
        if not suspicious:
            icon = "✅"
            verdict = f"No suspicious object detected. '{label}' is not a threat category."
        elif confidence >= 0.75 and coverage_pct >= 20:
            icon = "🚨"
            verdict = "High-confidence threat detected. Explanation strongly supported."
        elif confidence >= 0.5 or coverage_pct >= 10:
            icon = "⚠️"
            verdict = "Suspicious object detected with moderate confidence.\nExplanation is partially supported."
        else:
            icon = "❓"
            verdict = "Low-confidence detection. Likely a false positive.\nManual inspection advised."

        return {
            "label": label,
            "confidence": confidence,
            "is_suspicious": suspicious,
            "mean_positive_attribution": positive_shap,
            "mean_negative_attribution": negative_shap,
            "high_attribution_coverage_pct": coverage_pct,
            "peak_attribution_region": (int(peak_x), int(peak_y)),
            "pixel_importance_map": pixel_importance,
            "strength_label": strength_label,
            "reliability": reliability,
            "icon": icon,
            "verdict": verdict,
        }

    # ------------------------------------------------------------
    # Main Explain Function
    # ------------------------------------------------------------
    def explain(self, image: Image.Image, max_evals: int = 1000):
        detections = self.detector.detect(image)
        top_det = self._get_top_detection(detections)

        if top_det is None:
            print("No detection found.")
            return None

        SHAP_SIZE = (640, 640)

        orig_w, orig_h = image.size
        sx, sy = SHAP_SIZE[0] / orig_w, SHAP_SIZE[1] / orig_h

        x1, y1, x2, y2 = top_det["bbox"]
        self._fixed_bbox = [x1 * sx, y1 * sy, x2 * sx, y2 * sy]

        full_img = np.array(image.resize(SHAP_SIZE))

        obj_w = max(8, int((x2 - x1) * sx))
        blur = max(3, obj_w // 15)

        print(f"[SHAP] object width={obj_w}px blur={blur}px")

        explainer = shap.Explainer(
            self._model_wrapper,
            masker=shap.maskers.Image(f"blur({blur},{blur})", full_img.shape),
            max_evals=max_evals,
            batch_size=32,
        )

        shap_values = explainer(np.array([full_img]))

        scaled_det = {**top_det, "bbox": self._fixed_bbox}
        conclusion = self._interpret_shap(shap_values, top_det)

        return full_img, scaled_det, shap_values, conclusion

def show_shap_result(full_img, scaled_det, shap_values, conclusion):
    pixel_importance = conclusion["pixel_importance_map"]

    fig, axes = plt.subplots(1, 3, figsize=(16, 5))
    fig.patch.set_facecolor("#0f0f23")

    # 1 — Full image with detection box
    axes[0].imshow(full_img)
    x1, y1, x2, y2 = scaled_det["bbox"]
    rect = patches.Rectangle(
        (x1, y1), x2 - x1, y2 - y1,
        linewidth=2, edgecolor="red", facecolor="none"
    )
    axes[0].add_patch(rect)
    axes[0].set_title(
        f"{conclusion['label']} — {conclusion['confidence']:.1%}",
        color="white", fontsize=12
    )
    axes[0].axis("off")

    # 2 — SHAP heatmap
    heatmap      = cv2.resize(pixel_importance, (full_img.shape[1], full_img.shape[0]))
    heatmap_norm = (heatmap - heatmap.min()) / (heatmap.max() - heatmap.min() + 1e-8)
    axes[1].imshow(full_img)
    axes[1].imshow(heatmap_norm, cmap="hot", alpha=0.55)
    px, py = conclusion["peak_attribution_region"]
    axes[1].plot(px, py, "c+", markersize=18, markeredgewidth=2, label="Peak SHAP")
    axes[1].set_title("SHAP Attribution Map", color="white", fontsize=12)
    axes[1].legend(loc="upper right", fontsize=8)
    axes[1].axis("off")

    # 3 — Verdict panel
    axes[2].axis("off")
    axes[2].set_facecolor("#1a1a2e")

    verdict_color = (
        "#ff4444" if "🚨" in conclusion["icon"]
        else "#ffaa00" if "⚠️" in conclusion["icon"]
        else "#44bb44"
    )

    panel_text = (
        f"Detection Result:\n"
        f"  Object      : {conclusion['label']}\n"
        f"  Confidence  : {conclusion['confidence']:.1%}\n\n"
        f"Explainability Analysis:\n"
        f"  Strength    : {conclusion['strength_label']} "
        f"({conclusion['high_attribution_coverage_pct']:.0f}%)\n"
        f"  Reliability : {conclusion['reliability']}\n\n"
        f"Final Verdict:\n"
        f"  {conclusion['icon']} {conclusion['verdict']}"
    )

    axes[2].text(
        0.05, 0.95, panel_text,
        ha="left", va="top",
        fontsize=9.5, color="white",
        transform=axes[2].transAxes,
        fontfamily="monospace",
        linespacing=1.6,
    )

    # highlight verdict line
    axes[2].text(
        0.05, 0.18,
        f"{conclusion['icon']} {conclusion['verdict']}",
        ha="left", va="top",
        fontsize=9, color=verdict_color, fontweight="bold",
        transform=axes[2].transAxes,
        fontfamily="monospace",
        linespacing=1.5,
    )

    axes[2].set_title("Analysis Report", color="white", fontsize=12)

    plt.tight_layout()
    plt.show()

    # --- stdout output (clean, no manual detection lines) ---
    print("\nDetection Result:")
    print(f"  - Object     : {conclusion['label']}")
    print(f"  - Confidence : {conclusion['confidence']:.1%}")
    print(f"\nExplainability Analysis:")
    print(f"  - Explanation Strength : {conclusion['strength_label']} "
          f"({conclusion['high_attribution_coverage_pct']:.0f}%)")
    print(f"  - Model Reliability    : {conclusion['reliability']}")
    print(f"\nFinal Verdict:")
    print(f"  {conclusion['icon']} {conclusion['verdict']}")

# MAIN

detector = XRayDetector("/content/drive/MyDrive/best.pt")
explainer = YOLOShapExplainer(detector)

uploaded = files.upload()
img_path = list(uploaded.keys())[0]
image = Image.open(img_path).convert("RGB")

result = explainer.explain(image, max_evals=100)
if result:
    full_img, scaled_det, shap_values, conclusion = result
    show_shap_result(full_img, scaled_det, shap_values, conclusion)